In [5]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[1]

2

In [5]:
a[2]

3

In [7]:
a[-2]

2

In [8]:
a[0]

1

In [6]:
a[-1]

3

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.empty(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
print(np.arange(5))

[0 1 2 3 4]


In [16]:
print(np.arange(0,8,2))

[0 2 4 6]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [18]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 1, 2])

In [19]:
np.delete(arr,2)

array([1, 2, 4, 5, 6])

In [20]:
np.delete(arr,1)

array([1, 3, 4, 5, 6])

In [21]:
arr = np.array([4, 3, 6, 5, 2, 1])

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6])

In [27]:
array_example = np.array([[[0, 1, 2, 3],4, 5, 6, 7]]),[[0, 1, 2, 3,]],[4, 5, 6, 7],[[0, 1, 2, 3],[4, 5, 6, 7]]



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 5) + inhomogeneous part.

In [28]:
a = np.arange(6)

In [29]:
print(a)

[0 1 2 3 4 5]


In [30]:
a = np.array([1, 2, 3, 4])

In [31]:
a.sum()

10

In [32]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [33]:
b.sum(axis=0)

array([3, 3])

In [34]:
b.sum(axis=1)

array([2, 4])

In [39]:
data = np.array([1, 2])
data

array([1, 2])

In [41]:
ones = np.ones(2)
ones

array([1., 1.])

In [42]:
data + ones

array([2., 3.])

In [43]:
data * data

array([1, 4])

In [44]:
data/data

array([1., 1.])

In [45]:
A = np.array([[2, 3, 6],
              [9, 7, 8],
              [1, 10, 15]])
print(A)

[[ 2  3  6]
 [ 9  7  8]
 [ 1 10 15]]


In [46]:
A.sum()

61

In [47]:
A.min()

1

In [48]:
A.min(axis=0)

array([1, 3, 6])

In [49]:
A.max()

15

In [50]:
A.max(axis=1)

array([ 6,  9, 15])

In [51]:
A.std()

4.15739709641549

In [52]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [53]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
np.random.random((3,2))

array([[0.01913415, 0.23617319],
       [0.4212912 , 0.31474227],
       [0.65761378, 0.69048591]])

In [6]:
data = np.array ([[3, 4], [5, 6]])
print(data)

[[3 4]
 [5 6]]


In [7]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [8]:
print (data + ones)

[[4. 5.]
 [6. 7.]]


In [9]:
data * data

array([[ 9, 16],
       [25, 36]])

In [10]:
data/data

array([[1., 1.],
       [1., 1.]])

In [11]:
data*2

array([[ 6,  8],
       [10, 12]])

In [12]:
data.max()

6

In [13]:
data.min()

3

In [14]:
data.sum()

18

In [15]:
A = np.array([[1.5, 1.3, 0.3, 0.5],
              [2.5, 0.05, 0.4, 0.55],
              [1.12, 0.8, 0.26, 1.56]])

print(A)

[[1.5  1.3  0.3  0.5 ]
 [2.5  0.05 0.4  0.55]
 [1.12 0.8  0.26 1.56]]


In [16]:
A.sum()

10.84

In [17]:
A.min()

0.05

In [18]:
A.min(axis=0)

array([1.12, 0.05, 0.26, 0.5 ])

In [19]:
A.max()

2.5

In [20]:
A.max(axis=1)

array([1.5 , 2.5 , 1.56])

In [21]:
A.std()

0.6830365209041819

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.random.random((3,2))

array([[0.94528664, 0.65758967],
       [0.52133685, 0.78920467],
       [0.9211079 , 0.31589127]])

In [25]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [26]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [27]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [28]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [29]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [30]:
data

array([[1, 2],
       [3, 4]])

In [31]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [32]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])